---
- hosts: all
  tasks:
    - become: true
      apt:
        update_cache: yes
        pkg:
          - zsh
          - tmux
          - procps
          - curl
          - git
          - ripgrep
          - sqlite3
          - emacs-nox
          - vim
          - make
    - file:
        path: ~/sources/
        state: directory
        mode: '0755'
    - git:
        repo: 'https://github.com/sata/dotfiles.git'
        dest: ~/sources/dotfiles
    - make:
        chdir: ~/sources/dotfiles
        target: ohmyzsh
    - make:
        chdir: ~/sources/dotfiles
        target: link
    - debug: var=out.stdout_lines
