---
- hosts: all
  tasks:
    - name: stuff I need
      become: true
      apt:
        update_cache: yes
        pkg:
          - zsh
          - tmux
          - procps
          - curl
          - libncurses5-dev
          - inotify-tools
          - vim
          - tig
          - xss-lock
          - okular
          - playerctl
          - i3
          - suckless-tools
          - texinfo
          - rofi
          - ripgrep
          - fonts-firacode
          - libtool-bin
          - sqlite3
          - shellcheck
          - ddcutil
          - ansible
          - vagrant
          - vagrant-libvirt
          - libvirt-daemon-system

          - cargo

          - gcc
          - cmake
          - build-essential
          - automake
          - autoconf
          - make
          - git

          - libgccjit0
          - libjansson-dev
          - libxaw7-dev
          - libjansson4
          - libgccjit-10-dev
          - libssl-dev
          - flex
          - xsltproc
          - libwxgtk3.0-gtk3-dev
          - libwxgtk3.0-gtk3-0v5
    - name: adding "{{ ansible_user }}" to libvirt
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: yes
    - file:
        path: ~/sources/
        state: directory
        mode: '0755'
    - git:
        repo: 'https://github.com/sata/dotfiles.git'
        dest: ~/sources/dotfiles
    - make:
        chdir: ~/sources/dotfiles
        target: ohmyzsh
    - make:
        chdir: ~/sources/dotfiles
        target: link
    - git:
        repo: git://git.sv.gnu.org/emacs.git
        dest: ~/sources/emacs
        version: feature/native-comp
    - make:
        chdir: ~/sources/emacs
        jobs: 2
    - become: yes
      make:
        chdir: ~/sources/emacs
        target: install
    - debug: var=out.stdout_lines
